### PR TITLE
Remove the coverage dependency constraint.

### LINKED ISSUE #2: Support for coverage 4.0
[coverage.py 4.0](http://nedbatchelder.com//blog/201508/coveragepy_40b1.html) changes the format for .coverage files and introduces an API for accessing the data so perhaps we won't need to poke around in the private internals any more.

It'd be good to make sure z3c.coverage can work with coverage.py 4.0.

### PR DESCRIPTION
**Pull request by jensens**
fixes #2

### CODE REVIEW

**Comment by jensens** [comment]
needs some love, cc @thet

**Comment by jensens** [comment]
I am pretty sure best is to get rid of z3c.coverage where used and use vanilla coverage checks in all Zope2 core packages at least.
I don't see any real win, we just fight with a tool depending on some non-api implementation specific details.

**Comment by thet** [comment]
At Alpine City Sprint I tried to update z3c.coverage to support coverage >= 4.0.

Converting the sampledata.pickle to sampledata.json was the easy part, but z3c.coverage uses coverage' internal data structures, which have also changed a lot and updating a pain. Also, z3c.coverage makes assumptions to the VCS system in use as it only supports SVN to get the revision (not sure, for what this is used).

I think it's not worth the effort to update z3c.coverage - I'm not sure about the benefit of this package at all. For Plone, we can easily remove the dependency from all buildout files.

**Comment by thet** [comment]
related: https://github.com/zopefoundation/z3c.coverage/issues/2

**Pull request closed without merging**
